; This file was auto-generated by drush make
core = 7.x

; Modules
projects[] = admin_menu
projects[] = advanced_form
projects[] = advanced_help
projects[] = backup_migrate
projects[] = context
projects[] = ctools
projects[] = custom_search
projects[] = date
projects[] = devel
projects[] = dhtml_menu
projects[] = entity 
projects[] = entityreference
projects[] = facebookshare
projects[] = faq
projects[] = features
projects[] = feeds
projects[] = feeds_tamper
projects[] = field_collection
projects[] = flag
projects[] = google_analytics
projects[] = image_resize_filter
projects[] = insert
projects[] = job_scheduler
projects[] = jquery_update
projects[] = legal
projects[] = libraries
projects[] = link 
projects[] = list_predefined_options
projects[] = metatag
projects[] = module_filter
projects[] = nice_menus
projects[] = omega_tools
projects[] = pathauto
projects[] = print
projects[] = rate
projects[] = rules
projects[] = simplehtmldom
projects[] = taxonomy_manager
projects[] = termcase
projects[] = token
projects[] = views
projects[] = views_nivo_slider
projects[] = votingapi
projects[] = webform
projects[] = youtube

; Themes
projects[zen][version] = "5.1"
projects[omega][version] = "3.1"

; custom modules
projects[SBD Footer][download][type] = "git"
projects[SBD Footer][download][url] = "git@bitbucket.org:spyderbytedesign/spyder-byte-design-footer-module.git"
projects[SBD Footer][type] = "module"

; Libraries
libraries[json2][download][type] = "git"
libraries[json2][download][url] = "git@bitbucket.org:spyderbytedesign/foodishi-libraries-json2.git"
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

libraries[nivo-slider][download][type] = "git"
libraries[nivo-slider][download][url] = "git@bitbucket.org:spyderbytedesign/foodishi-libraries-nivo-slider.git"
libraries[nivo-slider][directory_name] = "nivo-slider"
libraries[nivo-slider][type] = "library"

libraries[krumo_0.2.1a_PHP5-Only][download][type] = "git"
libraries[krumo_0.2.1a_PHP5-Only][download][url] = "git@bitbucket.org:spyderbytedesign/foodishi-libraries-krumo.git"
libraries[krumo_0.2.1a_PHP5-Only][directory_name] = "krumo_0.2.1a_PHP5-Only"
libraries[krumo_0.2.1a_PHP5-Only][type] = "library"

libraries[jquery.cycle][download][type] = "git"
libraries[jquery.cycle][download][url] = "git@bitbucket.org:spyderbytedesign/foodishi-libraries-jquery.cycle.git"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

libraries[dompdf][download][type] = "git"
libraries[dompdf][download][url] = "git@bitbucket.org:spyderbytedesign/foodishi-libraries-dompdf.git"
libraries[dompdf][directory_name] = "dompdf"
libraries[dompdf][type] = "library"

ibraries[ckeditor][download][type] = "git"
libraries[ckeditor][download][url] = "git@bitbucket.org:spyderbytedesign/ckeditor.git"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
libraries[galleria][download][type] = "git"
libraries[galleria][download][url] = "git@bitbucket.org:spyderbytedesign/galleria.git"
libraries[galleria][directory_name] = "galleria"
libraries[galleria][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"
